/**
 * @piclaw/agent-kernel — single import surface for pi-agent-core / pi-ai in PiClaw.
 * Upgrade pi versions here; runtime and cloud consume this package only.
 */
export {
  agentLoop,
  agentLoopContinue,
  runAgentLoop,
  runAgentLoopContinue,
  convertToLlm,
  compact,
  shouldCompact,
  estimateContextTokens,
  estimateTokens,
  findCutPoint,
  prepareCompaction,
  generateSummary,
  DEFAULT_COMPACTION_SETTINGS,
  type AgentContext,
  type AgentEvent,
  type AgentLoopConfig,
  type AgentMessage,
  type AgentTool,
  type AgentToolResult,
  type StreamFn,
  type ThinkingLevel,
} from "@earendil-works/pi-agent-core";

export {
  Type,
  contentText,
  createModels,
  createAssistantMessageEventStream,
  fauxAssistantMessage,
  fauxProvider,
  fauxToolCall,
  getSupportedThinkingLevels,
  clampThinkingLevel,
  InMemoryModelsStore,
  type Api,
  type AssistantMessage,
  type AssistantMessageEvent,
  type AssistantMessageEventStream,
  type AuthEvent,
  type AuthPrompt,
  type AuthType,
  type Context,
  type Credential,
  type CredentialInfo,
  type CredentialStore,
  type ImageContent,
  type Message,
  type Model,
  type Models,
  type ModelsRefreshResult,
  type ModelsSimpleStreamOptions,
  type ModelsStoreEntry,
  type MutableModels,
  type OAuthCredential,
  type Provider,
  type RefreshModelsContext,
  type SimpleStreamOptions,
  type StreamOptions,
  type TextContent,
  type Tool,
  type ToolCall,
  type ToolResultMessage,
  type Usage,
  type UserMessage,
} from "@earendil-works/pi-ai";

export {
  CLOUD_KERNEL_PROVIDER_ID,
  createCloudKernelModel,
  createCloudKernelRuntime,
  type CloudKernelConfig,
  type CloudKernelRuntime,
} from "./provider";
