-- Application-layer ownership checks replace request-scoped PostgreSQL identity.
-- Keep ownership columns and indexes, but stop enforcing the retired RLS model.

ALTER TABLE sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE session_cursors NO FORCE ROW LEVEL SECURITY;
ALTER TABLE token_usage NO FORCE ROW LEVEL SECURITY;
ALTER TABLE scheduled_tasks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE subagent_runs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE api_keys NO FORCE ROW LEVEL SECURITY;
ALTER TABLE user_daily_usage NO FORCE ROW LEVEL SECURITY;
ALTER TABLE session_compactions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE session_compaction_backoffs NO FORCE ROW LEVEL SECURITY;

ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE session_cursors DISABLE ROW LEVEL SECURITY;
ALTER TABLE token_usage DISABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE subagent_runs DISABLE ROW LEVEL SECURITY;
ALTER TABLE subagent_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_daily_usage DISABLE ROW LEVEL SECURITY;
ALTER TABLE session_compactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE session_compaction_backoffs DISABLE ROW LEVEL SECURITY;
ALTER TABLE media DISABLE ROW LEVEL SECURITY;
ALTER TABLE message_media DISABLE ROW LEVEL SECURITY;
ALTER TABLE session_recordings DISABLE ROW LEVEL SECURITY;
ALTER TABLE session_recording_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_keychain DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_run_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE web_push_vapid_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE web_push_subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE autoresearch_runs DISABLE ROW LEVEL SECURITY;
